name: 'JS static analysis and lint'
description: 'Run standard static analysis and lint tasks on a js subproject'
inputs:
  project:
    description: 'Which project (by subdirectory) to run checks on'
    required: true
  circular_deps:
    description: 'Whether to run circular dependency checks, which only work on certain projects'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: 'js file lint'
      shell: bash
      run: |
        yarn stylelint ${{ inputs.project }}/**/*.js ${{ inputs.project }}/*.js
        yarn eslint .*.js ${{ inputs.project }}/**/*.js
    - name: 'json file lint'
      shell: bash
      run: yarn eslint --max-warnings 0 --ext .json ${{ inputs.project }}
    - name: 'formatting checks'
      shell: bash
      run: yarn prettier --ignore-path .eslintignore --check ".*.@(js|yml)" "${{ inputs.project }}/**/*.@(js|json|md|yml)"
    - name: 'typechecks'
      shell: bash
      run:  yarn flow check ${{ inputs.project }}
    - name: 'circular deps (if applicable)'
      shell: bash
      run: "[[ -n '${{ inputs.circular_deps }}' ]] && yarn madge --no-spinner --no-color --circular ${{ inputs.project }}/src/index.js || echo 'no circular deps checking for ${{ inputs.project }}'"
