# This workflow runs tests and lint on branch pushes that touch the
# shared-data project or its CI configuration.

name: 'shared-data lint/test'

on:
  push:
    paths:
      - 'Makefile'
      - 'shared-data/*/**'
      - '.github/workflows/shared-data-lint-test.yaml'
      - '.github/actions/python/**'
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    paths:
      - 'Makefile'
      - 'shared-data/*/**'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  python-lint:
    name: 'shared-data package python lint'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-node@v1'
        with:
          node-version: '12'
      - uses: 'actions/setup-python@v2'
        with:
          python-version: '3.7'

      - uses: './.github/actions/python/setup'
        with:
          project: 'shared-data/python'
      - name: Lint
        run: make -C shared-data/python lint
  python-test:
    name: 'shared-data package python tests'
    needs: [python-lint]
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-node@v1'
        with:
          node-version: '12'
      - uses: 'actions/setup-python@v2'
        with:
          python-version: '3.7'
      - uses: './.github/actions/python/setup'
        with:
          project: 'shared-data/python'
      - name: 'set complex environment variables'
        id: 'set-vars'
        uses: actions/github-script@v3
        with:
          script: |
            const branch = context.ref.replace(/^refs\/(?:tags|heads)\//, '')
            const tag = context.ref.startsWith('refs/tags/') ? branch : ''
            console.log('run number is', context.runNumber)
            const buildNumber = context.runNumber + 10000
            core.exportVariable('OT_BRANCH', branch)
            core.exportVariable('OT_TAG', tag)
            core.exportVariable('OT_BUILD', buildNumber)
      - name: Test
        run: make -C shared-data/python test
        # creds and repository configuration for deploying python wheels
      - if: contains(matrix.os, 'ubuntu') && (github.event_name == 'push') && !startsWith(env.OT_TAG, 'v')
        name: 'set test pypi creds'
        run: |
          echo "::set-env name=PYPI_PASSWORD::${{ secrets.OT_TEST_PYPI_PASSWORD }}"
          echo "::set-env name=PYPI_URL::'https://test.pypi.org/legacy/'"
      - if: contains(matrix.os, 'ubuntu') && (github.event_name == 'push') && startsWith(env.OT_TAG, 'v')
        name: 'set pypi creds'
        run: |
          echo "::set-env name=pypi_password::${{ secrets.OT_PYPI_PASSWORD }}"
          echo "::set-env name=twine_repository_url::'https://upload.pypi.org/legacy/'"

      - if: contains(matrix.os, 'ubuntu') && (github.event_name == 'push')
        uses: './.github/actions/python/setup'
        with:
          project: 'shared-data/python'
      - if: contains(matrix.os, 'ubuntu') && (github.event_name == 'push')
        name: Deploy shared-data wheel to pypi
        run: |
          QUIET=1 BUILD_NUMBER=${OT_BUILD} make -C shared-data deploy-py twine_repository_url=${PYPI_URL} pypi_username=opentrons pypi_password=${PYPI_PASSWORD}
